name: CI

on:
  pull_request:
    branches: [master]

env:
  GITHUB_CONTEXT: ${{toJson(github)}}
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
  GITHUB_HEAD_REF: ${{github.head_ref}}
  GITHUB_PULL_REQUEST_HEAD_SHA: ${{github.event.pull_request.head.sha}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    name: Mutating...
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      # - name: DEBUG
      #   run: echo ${{github.sender.login}}
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Review Api
        run: yarn review:api
      - name: Spec
        env:
          GITHUB_APP_NAME: mutationapp
          MUTATE_API_URL: ${{env.HEROKU_REVIEW_APP_URL}}
          DATABASE_URL: ${{secrets.DATABASE_TEST_URL}}
          STORAGE_URL: ${{secrets.STORAGE_TEST_URL}}
          INTEGRATION_API_KEY: ${{secrets.INTEGRATION_API_KEY}}
          MUTATE_REPOSITORY_TOKEN: ${{secrets.MUTATE_REPOSITORY_TOKEN}}
        run: yarn spec
      - name: Stryker
        run: yarn stryker
      - name: Mutate
        env:
          MUTATE_STRATEGY: 'all'
          MUTATE_API_URL: ${{env.HEROKU_REVIEW_APP_URL}}
          MUTATE_REPOSITORY_TOKEN: ${{secrets.MUTATE_REPOSITORY_TOKEN}}
          MUTATE_PULL_NUMBER: ${{ github.event.pull_request.number }}
          MUTATE_PULL_OWNER: ${{github.event.pull_request.base.user.login}}
        run: echo "The PR number is $MUTATE_PULL_NUMBER and mutate url $MUTATE_API_URL" && yarn mutate
      - name: Review Web
        run: yarn review:web
